"""Add interview_analysis

Revision ID: ef36bd1f1752
Revises: 
Create Date: 2026-01-09 16:12:07.803809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef36bd1f1752'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recordings_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_analysis_results_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_interview_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_candidate_logs_id'), table_name='candidate_logs')
    op.drop_index(op.f('ix_candidate_logs_interview_id'), table_name='candidate_logs')
    op.drop_index(op.f('ix_candidate_logs_token'), table_name='candidate_logs')
    op.drop_table('candidate_logs')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_interview_analysis_id'), table_name='interview_analysis')
    op.drop_index(op.f('ix_interview_analysis_interview_id'), table_name='interview_analysis')
    op.drop_table('interview_analysis')
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_table('interviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('interviews_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('candidate_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('candidate_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='interviews_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    op.create_table('interview_analysis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_percentages', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('analysis_report', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('effective_risk_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('interview_analysis_interview_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_analysis_pkey'))
    )
    op.create_index(op.f('ix_interview_analysis_interview_id'), 'interview_analysis', ['interview_id'], unique=False)
    op.create_index(op.f('ix_interview_analysis_id'), 'interview_analysis', ['id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('questions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('examples', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name='questions_interview_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='questions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('candidate_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('event', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('candidate_logs_pkey'))
    )
    op.create_index(op.f('ix_candidate_logs_token'), 'candidate_logs', ['token'], unique=False)
    op.create_index(op.f('ix_candidate_logs_interview_id'), 'candidate_logs', ['interview_id'], unique=False)
    op.create_index(op.f('ix_candidate_logs_id'), 'candidate_logs', ['id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('analysis_results_interview_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('analysis_results_pkey'))
    )
    op.create_index(op.f('ix_analysis_results_interview_id'), 'analysis_results', ['interview_id'], unique=False)
    op.create_index(op.f('ix_analysis_results_id'), 'analysis_results', ['id'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('answer_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('recordings_interview_id_fkey')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_recordings_question_id_questions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('recordings_pkey'))
    )
    op.create_index(op.f('ix_recordings_id'), 'recordings', ['id'], unique=False)
    # ### end Alembic commands ###
